# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from bs4 import BeautifulSoup


class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver = webdriver.Chrome()
    self.vars = {}
    self.driver.get("https://www.cbsnews.com/")
    self.driver.set_window_size(1366, 728)
    element = self.driver.find_element(By.CSS_SELECTOR, ".site-nav__item--news > .site-nav__item-anchor")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".site-nav__item--news > .site-nav__item-anchor")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".site-nav__item--world .site-nav__item-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".site-nav__item--news > .site-nav__item-anchor").click()

    self.driver.switch_to.frame(12)
    self.driver.find_element(By.CSS_SELECTOR, "#cbb > svg").click()
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, ".site-nav__item--news > .site-nav__item-anchor").click()
    self.driver.find_element(By.LINK_TEXT, "US").click()
    self.driver.execute_script("window.scrollTo(0,50)")
    self.driver.execute_script("window.scrollTo(0,600)")
    self.driver.execute_script("window.scrollTo(0,690)")
  
